### ISSUE TITLE
PT look up errors

### ISSUE THREAD

**Issue by RevThreat** [Te-k/harpoon#114]
```
Traceback (most recent call last):
  File "/usr/local/bin/harpoon", line 11, in <module>
    load_entry_point('harpoon==0.1.3', 'console_scripts', 'harpoon')()
  File "/usr/local/lib/python3.5/dist-packages/harpoon-0.1.3-py3.5.egg/harpoon/main.py", line 61, in main
    plugins[args.command].run(config, args, plugins)
  File "/usr/local/lib/python3.5/dist-packages/harpoon-0.1.3-py3.5.egg/harpoon/commands/domain.py", line 169, in run
    'first': d['time_first_o'].astimezone(pytz.utc),
ValueError: astimezone() cannot be applied to a naive datetime
```

**Comment by Te-k** [comment]
Thanks for reporting this bug, which version are you currently using ? I think I have fixed that bug with the current development version, could you try to test this with the version in the github repo ?
Thanks

**Comment by RevThreat** [comment]
Yo, sorry i forgot that i had put this one in. And made a new one the other day :/ You can ignore that recent one, so this is happening even with the latest updates. (if you go look at the new issue i made, you'll see that some IP's work, and some dont) again I'm sorry for making another issue. Totally forgot I made this one..

**Comment by Te-k** [comment]
Thanks, let's continue in the other issue #117
