### ISSUE TITLE
pipl service I will puts api. And numverify.? 

### ISSUE THREAD

**Issue by darknodi** [Te-k/harpoon#118]
pipl service I will puts api. And numverify.?  @mlaferrera @marrouchi @freyfogle @sidtechnical @Neo23x0

**Comment by Te-k** [comment]
I don't get what is your issue exactly ? Could you explain more ?

**Comment by darknodi** [comment]
Please. Add more Scopes in the Script. as osintS34rCh.py from these Service API's please. 
from username to.... to phones, emails, to age, gender, name, last name. 
from domain to. phones, etc etc.
These are Full API's
pipl.com
ekata.com
numverify.com
dataprovider.com
opencnam.com

https://rocketreach.co
https://shodan.com
https://hunter.io  @Te-k

**Comment by Te-k** [comment]
Good ideas, feel free to submit Pull Requests, I will just develop what is needed and useful for me, so most of these won't be implemented until I need them.

**Comment by darknodi** [comment]
@Te-k you don't want ?

**Comment by Te-k** [comment]
I am not paid to do that work, so if it is not fun or useful for my daily job, I won't develop it. But I would be happy to accept pull requests.

**Comment by darknodi** [comment]
liar
