### ISSUE TITLE
Fixes usage of maxmind geopip db

### ISSUE THREAD

**Issue by Te-k** [Te-k/harpoon#120]
It is no longer available without registration : https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

The best way is likely to rely on geoipupdate and check the path https://github.com/maxmind/geoipupdate/releases

**Comment by Te-k** [comment]
Best solution would be :
* Ask to install geoipupdate and configure it https://github.com/maxmind/geoipupdate/releases (configuration from https://www.maxmind.com/en/accounts/161197/license-key/GeoIP.conf )
* Check if geoipupdate exist
* Check when the files where downloaded last, if not recent run it
* Then use the files stored in `/var/lib/GeoIP`

**Comment by joaociocca** [comment]
is this why config -u breaks on `Downloading MaxMind GeoIP Database`?

**Comment by Te-k** [comment]
Yes, I have to fix that soon

**Comment by Te-k** [comment]
Fixed, can you try with version 0.1.4 @joaociocca ?

**Comment by joaociocca** [comment]
`config -u` done! thank you, @Te-k

**Comment by joaociocca** [comment]
Could this other error be related?
```
kali@kali:~/harpoon$ sudo harpoon ip info <ip>
Traceback (most recent call last):
  File "/usr/local/bin/harpoon", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/harpoon/main.py", line 61, in main
    plugins[args.command].run(config, args, plugins)
  File "/usr/local/lib/python3.8/dist-packages/harpoon/commands/ip.py", line 171, in run
    ipinfo = self.ipinfo(ip)
  File "/usr/local/lib/python3.8/dist-packages/harpoon/commands/ip.py", line 132, in ipinfo
    citydb = geoip2.database.Reader(self.geocity)
  File "/usr/lib/python3/dist-packages/geoip2/database.py", line 86, in __init__
    self._db_reader = maxminddb.open_database(fileish, mode)
  File "/usr/lib/python3/dist-packages/maxminddb/__init__.py", line 39, in open_database
    return maxminddb.extension.Reader(database)
FileNotFoundError: No such file or directory: '/usr/share/GeoIP/GeoLite2-City.mmdb'
```

**Comment by Te-k** [comment]
Yes, because of changes in MaxMind for geolocation, you now need to install [geoipupdate](https://github.com/maxmind/geoipupdate), [confiture it correctly](https://dev.maxmind.com/geoip/geoipupdate/) and run it to have the last updated databases, and harpoon is using that files (make sure you to have GeoLite2-Country GeoLite2-City GeoLite2-ASN as EditionIDs).

**Comment by Te-k** [comment]
Is it solved for you ? Let me know if the doc is not clear, I will update that

**Comment by joaociocca** [comment]
sorry for the delay! it's fixed over here, thanks!

**Comment by Te-k** [comment]
Cool !
