### ISSUE TITLE
Static analysis has some interesting results

### ISSUE THREAD

**Issue by TomMD** [Te-k/harpoon#142]
I saw your [twitter comment](https://twitter.com/tenacioustek/status/1333752207779508225) and decided to run some analysis tools in response.  N.B. You can turn checkers these on for PRs by [installing the app](https://github.com/marketplace/muse-dev) (disclaimer: my company's app).

The results [are here](https://console.muse.dev/result/TomMD/harpoon/01ERJXXDVRMP0SSQMYB9NWKPDW?tab=results).  They are from semgrep and bandit - both of which are open source python analysis tools.  I'm not sure why Facebook's Python type checker (pyre) didn't work but if that's something you'd like then we can definitely work through it.

**Comment by Te-k** [comment]
Thanks, that's useful, I will have a look !
