### ISSUE TITLE
Greynoise & Config

### ISSUE THREAD

**Issue by XavCC** [Te-k/harpoon#156]
Hi,

with `harpoon-0.1.6`  I got an issue with greynoise

```
harpoon greynoise -i IP
Invalid configuration for this plugin, quitting...
```

The recent changes were made with greynoise API community https://github.com/Te-k/harpoon/blob/master/harpoon/commands/gn.py

And now no config appears in `harpoon config -c` for greynoise

So I'm lost :thinking:

**Comment by christalib** [comment]
Going to look into it

**Comment by XavCC** [comment]
Well,

my bad.

While `$ harpoon config` I just add using `vi`:
```
[GreyNoise]
key: api.greynoise.io/v3/community
api_type: community
intel: true
```
A bit confusing when given a list to complete that did not contain `greynoise`.

if you agree @christalib 
I would suggest 
+ To provide a completed list to fill in `config`
or
+ To clarify the documentation about "how to fill the needs in config"
+ To close this actual issue due to my bad attentiveness

**Comment by christalib** [comment]
Ok, we'll get that done. Thank for reporting!
