### ISSUE TITLE
Upgrade censys plugin

### ISSUE THREAD

**Issue by Te-k** [Te-k/harpoon#160]
Adds https://twitter.com/zakirbpd/status/1476607511050391580

**Comment by presianbg** [comment]
Hi,
Thanks for the wonderful project.
Trying to use the `censys` subdomain module, but looks like the method `get_subdomains` is not implemented yet ? 
Is it a bug or known issue ?
```
    subdomains = censys_cmd.get_subdomains(
AttributeError: 'CommandCensys' object has no attribute 'get_subdomains'

```

**Comment by Te-k** [comment]
Hi, it is indeed a bug, I think I removed this part of the command because it was not very efficient and consuming a lot of Censys API. I have removed the part of the code that was referenced it.

**Comment by Te-k** [comment]
Done
