### ISSUE TITLE
Github key doesn't exist in config file

### ISSUE THREAD

**Issue by jJit0** [Te-k/harpoon#161]
Bonjour Etienne,

Tout d'abord, je veux te remercier pour cet outil génialissime, c'est l'un des meilleurs que j'ai jamais vu en OSINT :smiley:
J'espère que tu pourra à l'avenir en rajouter d'autres modules, comme:

`Wigle` pour réperer les SSID des bornes wi-fi du monde entier
`Psbdmp` pour réperer les bases de données de pastebin
`Zoomeye` l'équivalent de Shodan et Censys
`Wolframalpha` qui peut être utilisé comme moteur de recherche à IA

Chacun de ces modules ont besoin d'une clé API, qu'on obtien gratuitement.

Je voulais signaler ce problème, lorsque je lance `harpoon config -c` tout à l'air bon, mais j'ai un `FAILED` devant github et hibp.
```
-github		 -> FAILED
-hibp		 -> FAILED
```
Or ces deux entrées n'existent pas dans le ficher de config `$HOME/.config/harpoon/config` ou même dans ton `example.conf`

Est-ce que je dois les ajouter manuellement, et si oui, connais-tu le pattern ? genre:
```
[Github]
key:
intel: true

[HIBP]
key:
intel: true
```

**Comment by Te-k** [comment]
Salut, merci pour les retours !
J'ai repêché ou créé des tickets pour Zoomeye #91, Wigle #162, Psbdmp #163 et Wolframalpha #164, n'hésite pas à oucrir des issues ou laisser des commentaires sur comment tu voudrais les voir implémenter. J'ai assez peu de temps à consacrer à harpoon ces temps-ci mais la plupart des plugins sont assez rapide à écrire (et n'hésite pas à proposer des PR).

Effectivement, il s'agit d'un bug, je viens de les ajouter avec 19426587e4c93eb502065110f4f2338001c691bb :
```
[Github]
token:

[HIBP]
key:
```

(Aucun des deux modules ne supporte intel pour le moment. Je crois que le module HIBP manque de tests, donc n'hésite pas si tu rencontre des problèmes, par contre la clé n'est pas gratuite, elle coute [3.5$ par mois maintenant](https://www.troyhunt.com/authentication-and-the-have-i-been-pwned-api/))

**Comment by jJit0** [comment]
Hello,

Merci pour le schéma, celui de Github c'est :ok: , en revanche, j'ai toujours un `FAILED` sur HIBP.
Ah mince, je pensais qu'on pouvais la tester gratuitement, DOMAGE!!! :disappointed:

Oui j'imagne que t'a pas assez du temps à consacrer sur Harpoon! le soucis, c'est que je ne suis pas un developpeur, je viens tout juste de débuter en Python :sweat_smile:

Je vais néanmoins suivre les templates dans le wiki, et essayer avec l'un des modules que j'ai proposé, et je te tienderais au courant.

**Comment by Te-k** [comment]
Si tu veux essayer d'écrire un plugin, il y a pas mal d'exemples dans le code, je serais heureux de revoir des un PR et donner des explications claires sur ce qui va ou pas.

Ce bug a bien été réglé ? Si oui je vais fermer le ticket

**Comment by jJit0** [comment]
Je n'ai pas encore eu le temps de le faire. Je vais essayer dès que je peux, en tenant compte des examples et des autre plugins.

Concernant Github, c'est bon, il n'y a plus de problème.

En revanche, j'ai retrouvé une clé HIBP qui fonctionne bien `curl -sH "hibp-api-key: $API-KEY" "https://haveibeenpwned.com/api/v3/breachedaccount/EMAIL"` donc si t'a besoin de faire des tests pour corriger le bug du plugin, je peux te la partager sans problème.

Tu peux fermer le ticket :smile:

**Comment by Te-k** [comment]
Ah oui, la clé m'intéresse, ca me permettra de tester le plugin. Tu peux m'envoyer un email à tek AT randhome.io

Merci !
