### ISSUE TITLE
Hybrid Analysis APIv2

### ISSUE THREAD

**Issue by jJit0** [Te-k/harpoon#166]
Hello Etienne,

Can you please update the Hybrid Analysis plugin to APIv2
The APIv1 had api_key and api_secret. v2 only needs api_key

Merci d'avance ;)

_Originally posted by @jJit0 in https://github.com/Te-k/harpoon/issues/42#issuecomment-1092177753_

**Comment by Te-k** [comment]
Thanks, I will work on that when I have time

**Comment by Te-k** [comment]
Info here : https://www.hybrid-analysis.com/docs/api/v2

**Comment by Te-k** [comment]
developed in dev, need to be merged in main
