### ISSUE TITLE
Installation error pg_config file not found

### ISSUE THREAD

**Issue by Mitscho** [Te-k/harpoon#201]
Hi,
When running the **pip3 install .** command to finalize the install I get **pg_config executable not found** and therefore **metadata generation failed**. I made sure that I have the right pip version and honestly I'm a bit clueless about what could be the issue. 
Thankful for any help.

**Comment by Te-k** [comment]
I think it is the postgresql dependency for pycrtsh, what system are you using? You need to be able to install [psycopg](https://www.psycopg.org/docs/install.html#prerequisites)

**Comment by Mitscho** [comment]
Hi, I tried again on a fresh Ubuntu installation and it worked. Thanks
