### ISSUE TITLE
Geolite data behind CloudFare -> config -u failing

### ISSUE THREAD

**Issue by rmarsollier** [Te-k/harpoon#57]
Hello,

I cant't manage to get config -u to work, the maxmind.com website being behind CloudFare, config -u fails everytime.

```
Updating plugin ip
Downloading MaxMind GeoIP Database
Traceback (most recent call last):
  File "/usr/local/bin/harpoon", line 11, in <module>
    load_entry_point('harpoon==0.1.1', 'console_scripts', 'harpoon')()
  File "/home/rbn/.local/lib/python3.5/site-packages/harpoon/main.py", line 52, in main
    plugins[args.command].run(config, args, plugins)
  File "/home/rbn/.local/lib/python3.5/site-packages/harpoon/commands/config.py", line 68, in run
    plugins[p].update()
  File "/home/rbn/.local/lib/python3.5/site-packages/harpoon/commands/ip.py", line 80, in update
    file_name, headers = urllib.request.urlretrieve('http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz')
  File "/usr/lib/python3.5/urllib/request.py", line 188, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable
```

**Comment by Te-k** [comment]
Have you tried downloading the file in your browser? I never had such issue, could it be some weird network problem ?

**Comment by rmarsollier** [comment]
I tried the URL from a browser, it works after the "CloudFare checking your browser" thing.

I guess python is not a valid brouter according to cloudfare 😅 i don't know if there is a way to workaround that from python.

The lack of these files makes the ip plugin buggish, any maybe some others.

**Comment by Te-k** [comment]
Indeed, Cloudfare is using javascript to test that the connection is not automated, so python is blocked. You can still download the files manually and put them in `~/.config/harpoon`, but it will be hard to update.
Except if these files are hosted on another domain not protected by Cloudfare, I don't see how to solve this issue. I can add a "Known bugs" in the doc to help other people with the same problem maybe ?

**Comment by rmarsollier** [comment]
Maybe we could add some try/except in the config and the plugins using these files to prevent python to throw exceptions at the user (first impression is important).

The exception could display a warning askin the user to manually do something (i.e. dl the files and put them in the config).

What do you thing about this?

**Comment by mlaferrera** [comment]
I'm not able to replicate this issue, perhaps it was a hiccup with cloud flare or something inline (i.e., web application firewall) blocked it?

**Comment by Te-k** [comment]
I added an exception for that, telling users to go to the known bug page, which explains how to download these files manually : https://github.com/Te-k/harpoon/wiki/Known-bugs

I think it is the only thing we can do. Please reopen it if you see anything else
