### ISSUE TITLE
"You can simply pip install the tool" doesnt work for me

### ISSUE THREAD

**Issue by javabeanz** [Te-k/harpoon#60]
I have spent 3 hours adding my own ssh keys, generating new ones, following github instructions for this isseu, cloned the repo myself, but still i get :   

Cloning ssh://git@github.com/javabeanz/harpoon to /tmp/pip-sLvtaY-build
git@github.com: Permission denied (publickey).

**Comment by Canon88** [comment]
Yes, I have the same problem.

**Comment by Te-k** [comment]
The problem likely comes from your ssh key in github, it is not a harpoon problem.  You can clone a repo without authentication with the https link instead : `git clone https://github.com/Te-k/harpoon.git`

**Comment by Te-k** [comment]
Ok, you are not the only one with this issue, it seems to come from harpoon package, I will have a look

**Comment by Te-k** [comment]
Can you confirm that you still have the same issue?
I have made different tests with python packages on my system and was not able to reproduce it.

**Comment by javabeanz** [comment]
you coud not reproduce it because you already setup the whole ssh/github configuration. for me, and perhaps for quite a few, https is the normal protocol for accessing github and settting up ssh/github can be quite a struggle. I was hugely frustrated by someone calling that "simply".

**Comment by Te-k** [comment]
Yes, I totally get that and agree that ideally the install should be easy without ssh key. I have tried without ssh access to github and it worked well, so I don't know if it is because there is another configuration difference between our systems or because the code was updated. Would you mind starting the installation from scratch ?

**Comment by javabeanz** [comment]
the clone action works, but the pip line failed at first. i had to repair and upgrade pip3. and required sudo to work.  still a lot easier then the ssh/git approach, thanks.
