### ISSUE TITLE
Is it possible to avoid 'vi' while configuration (at least for beginners) ?

### ISSUE THREAD

**Issue by sidtechnical** [Te-k/harpoon#62]
Big fan of `vi`. However, I would avoid that keeping Unix beginners in mind.

The command `harpoon config` opens the config file in vi as per line 78 of  `harpoon/harpoon/commands/config.py` file:

` subprocess.call(os.environ.get('EDITOR', 'vi') + ' ' + configpath, shell=True)`

Can it be any GUI based text editor, for example, `gedit`?

Just a suggestion from usability point of view.

**Comment by Te-k** [comment]
Good idea, could you check the $EDITOR environment variable first and then use something by default ? I would suggest nano instead of vi tho, I totally guess that everyone is not vi fan but nanon seems to be easier.

**Comment by Te-k** [comment]
It works, not sure why this is still open, I close
