### ISSUE TITLE
Does it support multiple data queries?

### ISSUE THREAD

**Issue by Canon88** [Te-k/harpoon#74]
I like this tool. Thank you very much.
However, it does not seem to support multi-data query? Or query through the load file. Supports CSV or TXT type files.

**Comment by Te-k** [comment]
What do you mean by multi-data query ? Querying several indicators at the same time ?
If yes, it is plugin dependent, like bitly supports it for instance : 
```
$ harpoon bitly -f short 
Date;Short URL;Long URL;Analytics;Aggregate;Aggregate Hash;User;Short URL Clicks;Long URL Clicks
03/23/2018 20:25:01;http://bit.ly/2ug2zq4;https://www.laquadrature.net/fr/conservation_operateurs;http://bit.ly/2ug2zq4+;2FWPBD2;No;2ug2zq4;2;7
03/27/2018 11:15:27;http://bit.ly/2Ge4D3m;https://github.com/Te-k/harpoon;http://bit.ly/2Ge4D3m+;2o1DhpZ;No;2Ge4D3m;0;213
```

If you want the same features in other plugins, feel free to propose Pull Requests, or open issues. I will likely develop only the features I need, but I hope other people will add features they need

**Comment by Canon88** [comment]
Sorry, I'm not careful enough. '-f' this parameter is ok. I like your tool very much. Thank you. I will close the problem.



xuh881026@foxmail.com
 
From: Tek
Date: 2018-03-27 17:17
To: Te-k/harpoon
CC: Canon88; Author
Subject: Re: [Te-k/harpoon] Does it support multiple data queries? (#74)
What do you mean by multi-data query ? Querying several indicators at the same time ?
If yes, it is plugin dependent, like bitly supports it for instance :
$ harpoon bitly -f short 
Date;Short URL;Long URL;Analytics;Aggregate;Aggregate Hash;User;Short URL Clicks;Long URL Clicks
03/23/2018 20:25:01;http://bit.ly/2ug2zq4;https://www.laquadrature.net/fr/conservation_operateurs;http://bit.ly/2ug2zq4+;2FWPBD2;No;2ug2zq4;2;7
03/27/2018 11:15:27;http://bit.ly/2Ge4D3m;https://github.com/Te-k/harpoon;http://bit.ly/2Ge4D3m+;2o1DhpZ;No;2Ge4D3m;0;213

If you want the same features in other plugins, feel free to propose Pull Requests, or open issues. I will likely develop only the features I need, but I hope other people will add features they need
