### ISSUE TITLE
Plugin-hibp: 'unifiedsearch' query method is more accurate.

### ISSUE THREAD

**Issue by Canon88** [Te-k/harpoon#81]
hi:
   I found that using the `unifiedsearch` query mode will make the result more accurate.
   I found this problem when comparing web queries with api queries.
But I don't know if this interface will bring other problems. I haven't seen a description of this method on the API documentation. However, the API interface can't find the data. You can query the result through this method. 
   E.g: `https://haveibeenpwned.com/api/v2/unifiedsearch/'account'`

   You can try adding this method to the plugin. :)

**Comment by Te-k** [comment]
Thanks, adding this as an improvement for the plugin :)

**Comment by Te-k** [comment]
HIBP is not supporting the V2 API anymore, I am closing this
