### ISSUE TITLE
ImportError: cannot import name 'ThreatGridError'

### ISSUE THREAD

**Issue by mbower** [Te-k/harpoon#88]
Fresh install on Ubuntu 18.04. Attempted to run `harpoon config` and got this:

```
Traceback (most recent call last):
  File "/usr/local/bin/harpoon", line 11, in <module>
    load_entry_point('harpoon==0.1.1', 'console_scripts', 'harpoon')()
  File "/usr/local/lib/python3.6/dist-packages/harpoon/main.py", line 31, in main
    plugins = init_plugins()
  File "/usr/local/lib/python3.6/dist-packages/harpoon/main.py", line 18, in init_plugins
    mod = __import__(plugin)
  File "/usr/local/lib/python3.6/dist-packages/harpoon/commands/ip.py", line 26, in <module>
    from pythreatgrid import ThreatGrid, ThreatGridError
ImportError: cannot import name 'ThreatGridError'
```

Python version: 3.6.5

**Comment by Te-k** [comment]
How did you install it ?

To fix it, you need to install [pyThreatGrid](https://github.com/Te-k/pythreatgrid) with a command like `pip install git+https://github.com/Te-k/pythreatgrid.git`

**Comment by mbower** [comment]
I just reinstalled it. Seems to have fixed it

`Collecting git+https://github.com/Te-k/pythreatgrid.git
  Cloning https://github.com/Te-k/pythreatgrid.git to /tmp/pip-y52zwyaz-build
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from pythreatgrid==0.1.1)
Installing collected packages: pythreatgrid
  Found existing installation: pythreatgrid 1.0.11
    Uninstalling pythreatgrid-1.0.11:
      Successfully uninstalled pythreatgrid-1.0.11
  Running setup.py install for pythreatgrid ... done
Successfully installed pythreatgrid-0.1.1
`

**Comment by Te-k** [comment]
Ok, weird. I close the bug then, please reopen it if you understand what happened.

**Comment by Te-k** [comment]
Just answered to you  in #108
